-- Canonical Supabase schema lives in supabase/migrations/.
--
-- For a fresh linked project, apply migrations with:
--   supabase db push
--
-- For local development, start Supabase locally and rebuild from migrations with:
--   supabase db reset
