import type { Expense, TaxConfig, YearProfile } from './types';
import { monthlyCuotas } from './ss';

/**
 * Generate the auto-created monthly cuota de autónomos as deductible expenses
 * (one per month). These are derived from the profile + config, not persisted,
 * so they never go stale. They are fully deductible for IRPF and carry no input
 * IVA (Seguridad Social contributions are not subject to IVA).
 */
export function cuotaExpenses(profile: YearProfile, cfg: TaxConfig): Expense[] {
  const cuotas = monthlyCuotas(profile, cfg);
  return cuotas.map((cents, i) => {
    const month = String(i + 1).padStart(2, '0');
    return {
      id: `cuota-${profile.year}-${month}`,
      date: `${profile.year}-${month}-28`,
      category: 'Cuota de autónomos (RETA)',
      amountCents: cents,
      deductiblePct: 100,
      inputIvaCents: 0,
      autoGenerated: true,
    };
  });
}
